# These are supported funding model platforms
github: # Replace with GitHub Sponsors
patreon: # Replace with Patreon
open_collective: # Replace with Open Collective
ko_fi: # Replace with Ko-fi
tidelift: # Replace with Tidelift
community_bridge: # Replace with Community Bridge
liberapay: # Replace with Liberapay
issuehunt: # Replace with IssueHunt
otechie: # Replace with Otechie
custom: # Replace with custom URLs
